apiVersion: v1
kind: ConfigMap
metadata:
  name: payment
  namespace: roboshop
  labels:
    project: roboshop
    tire: app
    component: payment
spec:
  data:
    CART_HOST: cart
    CART_PORT: 8080
    USER_HOST: user
    USER_PORT: 8080
    AMQP_HOST: rabbitmq
---
apiVersion: v1
kind: Secret 
metaadata:
  name: payment
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    tire: app
    component: payment
spec:
  type: Opaque
  data:
    AMQP_USER: "cm9ib3Nob3A="
    AMQP_PASS: "cm9ib3Nob3AxMjM="

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    tire: app
    component: payment
spec:
  replicas: 1
  selector: 
    labelsFrom:
      project: roboshop
      environment: dev
      tire: app
      component: payment
  template:
    metadata:
      labels:
        project: roboshop
        environment: dev
        tire: app
        component: payment
    spec:
    containers:
    - name: payment
      image: ramslella/payment
      envFrom: 
      - configMapRef:
        name: payment
      - secretRef:
        name: payment 

---
apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    tier: app
    component: shipping
spec:
  selector:
    labelsFrom:
      project: roboshop
      environment: dev
      tier: app
      component: shipping
  ports:
    protocol: TCP
    port: 8080
    targetPort: 8080
