apiVersion: v1
kind: ConfigMap
metadata:
  name: cart
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    component: cart
    tire: app
spec:
  data:
    REDIS_HOST: "redis"
    CATALOGUE_HOST: "catalogue"
    CATALOGUE_PORT: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    component: cart
    tire: app
spec:
  selector:
    matchLabels:
      project: roboshop
      environment: dev
      component: cart
      tire: app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: cart
  namespace: roboshop
  labels: 
    project: roboshop
    environment: dev
    component: cart
    tire: app
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      environment: dev
      component: cart
      tire: app
  template:
    metadata:
     labels: 
      project: roboshop
      environment: dev
      component: cart
      tire: app
    spec:
      containers:
      - name: cart
        image: ramslella/cart
        envFrom:
        - configMapRef:
          name: cart

