apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping
  namespece: roboshop
  labels:
    project: roboshop
    environment: dev
    tire: app
    component: shipping
spec: 
  data:
    CART_ENDPOINT: "cart:8080"
    DB_HOST: "mysql"
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    tire: app
    component: shipping
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      environment: dev
      tire: app
      component: shipping
  template:
    metadata:
      labels:
        project: roboshop
        environment: dev
        tire: app
        component: shipping
    spec:
      containers:
      - name: shippping
        image: ramslella/shipping 
        envFrom:
        - configMapRef:
          name: shipping 

---

apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    tire: app
    component: shipping
spec:
  selector:
    matchLabels:
      project: roboshop
      environment: dev
      tire: app
      component: shipping
  ports:
    protocol: TCP
    port: 8080
    targrtPort: 8080

