apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq
  namespace: rabbitmq
  labels:
    project: roboshop
    environment: dev
    tire: database
    component: rabbitmq
spec:
  data:
    USER: "cm9ib3Nob3A="
    PASSWORD: "cm9ib3Nob3AxMjM="


---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: rabbitmq
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    tire: database
    component: rabbitmq
spec:
  replicas: 1
  selector: 
    matchLabels:
      project: roboshop
      environment: dev
      tire: app
      component: shipping
  template:
      metadata:
        labels:
          project: roboshop
          environment: dev
          tire: app
          component: shipping
  spec:
    containers:
    - name: rabbitmq
      image: rabbitmq
      envFrom:
      - secretRef:
         name: rabbitmq 

---

apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    tire: database
    component: rabbitmq
spec:
  selector:
    matchLabels:
      project: roboshop
      environment: dev
      tire: database
      component: rabbitmq
  ports:
  - protocol: TCP
    port: 5672
    targetPort: 5672
