# apiVersion: v1
# kind: Secret
# metadata:
#   name: redis
#   namespace: roboshop
#   labels:
#     project: roboshop
#     environment: dev
#     tire: database
#     component: redis
# spec:
#   data:


---

apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    tire: app
    component: catalogue
spec:
  data:
    MONGO_URL: "mongodb://mongodb:27017/catalogue"
    MONGO: "true"

---

apiVersion: apps/v1
kind: Deployment
metadata: 
  name: catalogue
  namespace: raboshop
  labels:
    project: roboshop
    environment: dev
    tire: app
    component: catalogue
spec:
  replicas: 1
  selector:
    matchLabels:
        project: roboshop
        environment: dev
        tire: app
        component: catalogue
  template:
    metadata:
      labels:
        project: roboshop
        environment: dev
        tire: app
        component: catalogue
    spec:
      containers:
      - name: catalogue
        images: ramslella/catalogue
        envFrom:
        - configMapRef:
          name: catalogue

---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    tire: app
    component: catalogue
spec:
  selector:
      project: roboshop
      environment: dev
      tire: app
      component: catalogue
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080

